import {
  BAND_PAD_TOP,
  COL_HALF_LEFT,
  COL_HALF_RIGHT,
  COL_NARROW_RIGHT,
  COL_THIRD_1,
  COL_THIRD_2,
  COL_THIRD_3,
  COL_WIDE_LEFT,
  MARGIN_X,
  NAV_HEIGHT,
  band,
  navBar,
} from './layout.ts'
import type { NavEntry, StarterTemplate } from './layout.ts'

/* ═══════════════════════════ 2 · TRADES / SERVICES ═══════════════════════════
 * Teaches: one band per service, a phone-first call to action above the fold, and that
 * duplicating a band is how you add the next service.
 */

const TRADES_NAV: readonly NavEntry[] = [
  ['Home', 'home'],
  ['Services', 'services'],
  ['Get a Quote', 'quote'],
]

/** Trades · Home. */
const TH_HERO_Y = NAV_HEIGHT // 72
const TH_SERVICES_Y = TH_HERO_Y + 424 // 496

/** Trades · Services. */
const TS_HEADER_Y = NAV_HEIGHT // 72
const TS_A_Y = TS_HEADER_Y + 200 // 272
const TS_B_Y = TS_A_Y + 400 // 672

/** Trades · Get a Quote. */
const TQ_HEADER_Y = NAV_HEIGHT // 72
const TQ_CONTACT_Y = TQ_HEADER_Y + 224 // 296
const TQ_AREA_Y = TQ_CONTACT_Y + 440 // 736

export const TRADES_TEMPLATE: StarterTemplate = {
  id: 'trades',
  pickerTitle: 'Trades & services',
  pickerLine: 'Phone-first, one band per service, and a quote page.',
  siteSettings: {
    businessName: '',
    tagline: 'Licensed, insured, and we show up when we say we will.',
    about: '',
    vibe: 'bold',
    styleNotes: '',
    colors: [],
  },
  pages: [
    {
      id: 'home',
      name: 'Home',
      blocks: [
        navBar('trade-home-nav', TRADES_NAV),
        band('trade-home-hero-band', TH_HERO_Y, 424),
        band('trade-home-services-band', TH_SERVICES_Y, 480),
        {
          id: 'trade-home-hero-title',
          x: MARGIN_X,
          y: TH_HERO_Y + 64,
          width: 624,
          height: 104,
          type: 'heading',
          text: 'Ridgeway Plumbing & Heating',
          copyMode: 'real',
          fromTemplate: true,
        },
        {
          id: 'trade-home-hero-photo',
          ...COL_NARROW_RIGHT,
          type: 'image',
          y: TH_HERO_Y + 64,
          height: 296,
          text: '',
          fit: 'cover',
          description:
            'A photo of you and your van, or you on a job. People hire the person, not the logo — a real photo beats a stock one every time.',
          fromTemplate: true,
        },
        {
          id: 'trade-home-hero-sub',
          x: MARGIN_X,
          y: TH_HERO_Y + 192,
          width: 560,
          height: 72,
          type: 'text',
          text: 'Licensed, insured, and serving the Annapolis Valley since 2011. Same-day emergency callouts.',
          copyMode: 'real',
          fromTemplate: true,
        },
        {
          id: 'trade-home-hero-cta',
          x: MARGIN_X,
          y: TH_HERO_Y + 288,
          width: 264,
          height: 56,
          type: 'button',
          text: 'Get a free quote',
          link: { kind: 'page', pageId: 'quote' },
          fromTemplate: true,
        },
        {
          id: 'trade-home-services-title',
          ...COL_HALF_LEFT,
          type: 'heading',
          y: TH_SERVICES_Y + BAND_PAD_TOP,
          height: 56,
          text: 'What we do',
          copyMode: 'real',
          fromTemplate: true,
        },
        {
          id: 'trade-home-service-1',
          ...COL_THIRD_1,
          type: 'text',
          y: TH_SERVICES_Y + 128,
          height: 240,
          text: 'Boilers & furnaces\n\nInstalls, servicing and repairs on gas, oil and electric. We carry common parts on the van so most jobs finish the same day.',
          copyMode: 'real',
          fromTemplate: true,
        },
        {
          id: 'trade-home-service-2',
          ...COL_THIRD_2,
          type: 'text',
          y: TH_SERVICES_Y + 128,
          height: 240,
          text: 'Bathrooms & wet rooms\n\nFull fit-outs and small upgrades. We handle the plumbing, tiling and the mess, and we tidy up before we leave.',
          copyMode: 'real',
          fromTemplate: true,
        },
        {
          // Deliberately the same size as the two written-out services either side of it:
          // side by side, the client sees both copy modes at once.
          id: 'trade-home-service-3',
          ...COL_THIRD_3,
          type: 'text',
          y: TH_SERVICES_Y + 128,
          height: 240,
          text: '',
          copyMode: 'generate',
          generateDescription:
            "Short blurb about our 24/7 emergency callout service — under an hour into town, no weekend surcharge, and we'll tell you the price before we start.",
          lengthHint: '40–60 words',
          fromTemplate: true,
        },
        {
          id: 'trade-home-services-cta',
          x: MARGIN_X,
          y: TH_SERVICES_Y + 392,
          width: 280,
          height: 56,
          type: 'button',
          text: 'See all our services',
          link: { kind: 'page', pageId: 'services' },
          fromTemplate: true,
        },
      ],
    },
    {
      id: 'services',
      name: 'Services',
      blocks: [
        navBar('trade-svc-nav', TRADES_NAV),
        band('trade-svc-header-band', TS_HEADER_Y, 200),
        band('trade-svc-a-band', TS_A_Y, 400),
        band('trade-svc-b-band', TS_B_Y, 440),
        {
          id: 'trade-svc-title',
          x: MARGIN_X,
          y: TS_HEADER_Y + BAND_PAD_TOP,
          width: 600,
          height: 64,
          type: 'heading',
          text: 'Our services',
          copyMode: 'real',
          fromTemplate: true,
        },
        {
          id: 'trade-svc-a-title',
          ...COL_HALF_LEFT,
          type: 'heading',
          y: TS_A_Y + BAND_PAD_TOP,
          height: 56,
          text: 'Boilers & furnaces',
          copyMode: 'real',
          fromTemplate: true,
        },
        {
          id: 'trade-svc-a-photo',
          ...COL_HALF_RIGHT,
          type: 'image',
          y: TS_A_Y + BAND_PAD_TOP,
          height: 304,
          text: '',
          fit: 'cover',
          description:
            "A job you're proud of. Before-and-after side by side works well if you have one.",
          fromTemplate: true,
        },
        {
          id: 'trade-svc-a-body',
          ...COL_HALF_LEFT,
          type: 'text',
          y: TS_A_Y + 120,
          height: 224,
          text: "What's included, roughly what it costs, and how long it takes. Two or three short paragraphs is plenty — people are checking you're the right trade, not reading a brochure.",
          copyMode: 'real',
          fromTemplate: true,
        },
        {
          id: 'trade-svc-b-title',
          ...COL_HALF_LEFT,
          type: 'heading',
          y: TS_B_Y + BAND_PAD_TOP,
          height: 56,
          text: 'Bathrooms & wet rooms',
          copyMode: 'real',
          fromTemplate: true,
        },
        {
          id: 'trade-svc-b-photo',
          ...COL_HALF_RIGHT,
          type: 'image',
          y: TS_B_Y + BAND_PAD_TOP,
          height: 304,
          text: '',
          fit: 'cover',
          description:
            'A finished job for this service. Daylight, phone camera is fine, wide enough to see the whole room.',
          fromTemplate: true,
        },
        {
          id: 'trade-svc-b-body',
          ...COL_HALF_LEFT,
          type: 'text',
          y: TS_B_Y + 120,
          height: 224,
          text: "This band is a copy of the one above. Add a service by duplicating it and changing the words and the photo — that's the whole trick to building this page.",
          copyMode: 'real',
          fromTemplate: true,
        },
        {
          id: 'trade-svc-b-cta',
          x: MARGIN_X,
          y: TS_B_Y + 360,
          width: 264,
          height: 56,
          type: 'button',
          text: 'Get a free quote',
          link: { kind: 'page', pageId: 'quote' },
          fromTemplate: true,
        },
      ],
    },
    {
      id: 'quote',
      name: 'Get a Quote',
      blocks: [
        navBar('trade-quote-nav', TRADES_NAV),
        band('trade-quote-header-band', TQ_HEADER_Y, 224),
        band('trade-quote-contact-band', TQ_CONTACT_Y, 440),
        band('trade-quote-area-band', TQ_AREA_Y, 336),
        {
          id: 'trade-quote-title',
          ...COL_WIDE_LEFT,
          type: 'heading',
          y: TQ_HEADER_Y + BAND_PAD_TOP,
          height: 64,
          text: 'Get a free quote',
          copyMode: 'real',
          fromTemplate: true,
        },
        {
          id: 'trade-quote-intro',
          x: MARGIN_X,
          y: TQ_HEADER_Y + 136,
          width: 704,
          height: 56,
          type: 'text',
          text: "Tell us what's going on and we'll come back to you within one working day.",
          copyMode: 'real',
          fromTemplate: true,
        },
        {
          id: 'trade-quote-contact-title',
          ...COL_HALF_LEFT,
          type: 'heading',
          y: TQ_CONTACT_Y + BAND_PAD_TOP,
          height: 56,
          text: 'Call, text or email',
          copyMode: 'real',
          fromTemplate: true,
        },
        {
          id: 'trade-quote-badges',
          ...COL_HALF_RIGHT,
          type: 'image',
          y: TQ_CONTACT_Y + BAND_PAD_TOP,
          height: 280,
          text: '',
          fit: 'contain',
          description:
            'Your licence numbers, insurer and trade association badges, as one image. This is the block that makes strangers trust you.',
          fromTemplate: true,
        },
        {
          id: 'trade-quote-contact-body',
          ...COL_HALF_LEFT,
          type: 'text',
          y: TQ_CONTACT_Y + 112,
          height: 280,
          text: '(902) 555-0188\nhello@ridgewayplumbing.ca\n\nMonday – Friday  7am – 6pm\nEmergencies, any hour\n\nWant a contact form here instead of a phone number? Write down the boxes you want people to fill in and BOSS will build the real form.',
          copyMode: 'real',
          fromTemplate: true,
        },
        {
          id: 'trade-quote-area-title',
          ...COL_HALF_LEFT,
          type: 'heading',
          y: TQ_AREA_Y + BAND_PAD_TOP,
          height: 56,
          text: 'Areas we cover',
          copyMode: 'real',
          fromTemplate: true,
        },
        {
          id: 'trade-quote-area-body',
          ...COL_HALF_LEFT,
          type: 'text',
          y: TQ_AREA_Y + 112,
          height: 160,
          text: '',
          copyMode: 'generate',
          generateDescription:
            "A friendly line naming the towns we cover — Wolfville, Kentville, New Minas and Berwick — and saying we'll still travel further for bigger jobs.",
          lengthHint: '2 sentences',
          fromTemplate: true,
        },
        {
          id: 'trade-quote-area-cta',
          x: COL_HALF_RIGHT.x,
          y: TQ_AREA_Y + 112,
          width: 264,
          height: 56,
          type: 'button',
          text: 'See what we do',
          link: { kind: 'page', pageId: 'services' },
          fromTemplate: true,
        },
      ],
    },
  ],
}
