// @vitest-environment node
import { describe, expect, it } from 'vitest'

import { v7BriefCrossChecks } from './lib/rules/brief.mjs'
import { PRINTED_ID_RE } from './lib/brief-parse.mjs'

/**
 * THE HARNESS TWIN OF V7'S INVENTORY CROSS-CHECK, on the one cell v2.5 changed.
 *
 * The Blocks cell now reads `{blocks} (+{N} drawn)` on a page with top-level
 * `penRegions`, so a page the client drew rather than blocked out stops advertising
 * itself as having nothing on it. Generator and validator have to agree on that
 * string, and the gate is a separate program that imports no app code — so the
 * agreement exists twice and has to be asserted twice. Editing only the TypeScript
 * gives a green `npm test` and a red gate twelve minutes later, which is exactly the
 * failure this file exists to make impossible.
 *
 * Mirrors `src/export/validate/rules/inkRules.test.ts` > "V07 — the inventory Blocks
 * cell counts drawn regions (v2.5)".
 */

const CTX = {}

const region = (id, overrides = {}) => ({
  id,
  kind: 'panel',
  confidence: 'clear',
  bbox: { x: 0, y: 0, w: 200, h: 200 },
  strokeIds: [],
  parentRegionId: null,
  setId: null,
  setIndex: null,
  text: null,
  ...overrides,
})

const siteWith = (penRegions) => ({
  schemaVersion: 1,
  submission: {
    id: '00000000-0000-4000-8000-000000000000',
    submittedAt: '2026-07-29T00:00:00Z',
    designCreatedAt: null,
    client: { name: 'Test', email: 'test@example.com' },
    appVersion: '1.0.0',
  },
  siteSettings: { businessName: 'Test', tagline: null, about: null, vibe: null, styleNotes: null, colors: [] },
  pages: [
    {
      id: 'pg_0001',
      name: 'Home',
      slug: 'home',
      height: 1600,
      screenshot: 'pages/01-home.png',
      blocks: [],
      penStrokes: [],
      ...(penRegions === null ? {} : { penRegions }),
    },
  ],
  assets: [],
});

const briefWith = (blocksCell) =>
  [
    '# Build brief — Test',
    '',
    '<!-- Generated by BOSS Blueprint 1.0.0 · submission 00000000-0000-4000-8000-000000000000 · 2026-07-29T00:00:00Z · schemaVersion 1 · DO NOT EDIT (regenerate instead) -->',
    '',
    '## Site inventory',
    '',
    '1 page. **Page 1 is the homepage.**',
    '',
    '| # | Page | Slug | Sketch (ground truth) | Blocks | Links out |',
    '|---|---|---|---|---|---|',
    `| 1 | Home | \`home\` | \`pages/01-home.png\` (1200×1600) | ${blocksCell} | — |`,
    '',
    '## Page walkthroughs',
    '',
    '### Page 1 — Home (`home`)',
    '',
  ].join('\n');

const inventoryProblems = (site, brief) =>
  v7BriefCrossChecks({ site, briefText: { text: brief } }, CTX).problems.filter((problem) =>
    problem.startsWith('inventory row'),
  );

describe('V07 twin — the inventory Blocks cell counts drawn regions (v2.5)', () => {
  const drawn = siteWith([region('reg_0001'), region('reg_0002')]);

  it('accepts the cell the generator emits for a page with drawn regions', () => {
    expect(inventoryProblems(drawn, briefWith('0 (+2 drawn)'))).toEqual([]);
  });

  it('BLOCKs a brief that still prints the bare block count on that page', () => {
    expect(inventoryProblems(drawn, briefWith('0'))).toEqual([
      'inventory row 1: block count "0" != 0 (+2 drawn)',
    ]);
  });

  it('counts only TOP-LEVEL regions — a nested one is described in its parent bullet', () => {
    const nested = siteWith([region('reg_0001'), region('reg_0002', { parentRegionId: 'reg_0001' })]);
    expect(inventoryProblems(nested, briefWith('0 (+1 drawn)'))).toEqual([]);
  });

  it('is byte-neutral for a page with no penRegions field at all', () => {
    expect(inventoryProblems(siteWith(null), briefWith('0'))).toEqual([]);
    expect(inventoryProblems(siteWith(null), briefWith('0 (+0 drawn)'))).not.toEqual([]);
  });
});

/**
 * THE HARNESS TWIN OF THE COPY-LIST COUNT (v2.5).
 *
 * The heading counts the NUMBERED LIST under it — `generate` blocks — and nothing
 * else. Copy that comes from ink is stated after the list with its own verbs and its
 * own counts, so the heading's number describes exactly one thing and no sentence in
 * the section has to correct it. Mirrors
 * `src/export/validate/rules/inkRules.test.ts` > "V07 — the copy-list heading counts
 * the list under it (v2.5)".
 */
describe('V07 twin — the copy-list heading counts the list under it (v2.5)', () => {
  const copyBrief = (heading) =>
    [briefWith('0 (+2 drawn)'), '', `## Copy you must write (${heading})`, '', ''].join('\n');

  const copyProblems = (site, brief) =>
    v7BriefCrossChecks({ site, briefText: { text: brief } }, CTX).problems.filter((problem) =>
      problem.startsWith('copy-list'),
    );

  const drawnCopy = siteWith([
    region('reg_0001', { kind: 'writing' }),
    region('reg_0002', { kind: 'textPlaceholder' }),
  ]);

  it('accepts the generate-block count, whatever the ink carries', () => {
    expect(copyProblems(drawnCopy, copyBrief('0 items'))).toEqual([]);
  });

  it('BLOCKs a heading that folds drawn regions back into the number', () => {
    expect(copyProblems(drawnCopy, copyBrief('2 items'))).toEqual([
      'copy-list header says 2, site.json has 0 generate block(s)',
    ]);
  });

  it('does not count a nested region or a drawn nav either', () => {
    const nested = siteWith([
      region('reg_0001', { kind: 'panel' }),
      region('reg_0002', { kind: 'writing', parentRegionId: 'reg_0001' }),
      region('reg_0003', { kind: 'navRow' }),
    ]);
    expect(copyProblems(nested, copyBrief('0 items'))).toEqual([]);
  });

  it('pluralizes on that count [N8]', () => {
    const one = siteWith([region('reg_0001', { kind: 'navRow' })]);
    expect(copyProblems(one, copyBrief('0 item'))).toEqual([
      'copy-list header pluralization "item" should be "items" [N8]',
    ]);
  });

  it('is byte-neutral for a package with no drawn copy', () => {
    expect(copyProblems(siteWith(null), copyBrief('0 items'))).toEqual([]);
  });
});

/**
 * THE HARNESS TWIN OF FIX A — the tightened printed-id regex (§3.3 rule 5 / V7).
 *
 * §4.8 mints every public id as its prefix + zero-padded DIGITS, so a client filename
 * that reads like one (`set_menu.jpg`, `reg_flow.png`) is not an id and must not make
 * V7 BLOCK a valid package. Mirrors `src/export/validate/rules/rules.test.ts` >
 * "does NOT read an innocent client filename as a printed id".
 */
describe('V07 twin — an innocent client filename is not read as a printed id (Fix A)', () => {
  const idProblems = (site, brief) =>
    v7BriefCrossChecks({ site, briefText: { text: brief } }, CTX).problems.filter((p) =>
      p.includes('does not exist in site.json'),
    );

  it('does not flag set_menu / reg_flow as unknown ids', () => {
    const brief = `${briefWith('0')}\nclient files: set_menu.jpg, reg_flow.png\n`;
    expect(idProblems(siteWith(null), brief)).toEqual([]);
  });

  it('still matches every real minted id and rejects alpha-body filenames', () => {
    const matches = (s) => new RegExp(PRINTED_ID_RE.source, PRINTED_ID_RE.flags).test(s);
    for (const id of ['pg_0001', 'blk_0001', 'nav_0001', 'stk_0001', 'reg_0001', 'set_0001', 'img_001']) {
      expect(matches(id)).toBe(true);
    }
    for (const stem of ['set_menu', 'reg_flow', 'img_hero']) {
      expect(matches(stem)).toBe(false);
    }
  });
});
