/**
 * V7 — BRIEF CROSS-CHECK (generator drift). `docs/export-format.md` §5 V7 and
 * §3.3 rules 2, 5, 7, 8.
 *
 * The brief is generated FROM `site.json`, so any disagreement between them is a
 * generator bug, never a client error. V7 is a bundle of independent cross-checks;
 * each one that fails names exactly what drifted.
 */

import { escapeClientText, unescapeClientText } from '../../brief/text.ts'
import { EXPORT_PAGE_WIDTH, type SiteJson } from '../../types.ts'
import { finding, type Finding, type PackageBundle } from '../types.ts'
import { eachBlock, eachClientString, emptySlots, generateBlocks } from '../walk.ts'

/** §3.3 rule 2 (v2.1) — the binding frame-tuple-anchored marker regexes, verbatim. */
export const WRITE_THIS_COPY_RE =
  /^\s*- \*\*(Heading|Text)\*\* [^(\n]*\((-?\d+(\.\d)?, ){3}-?\d+(\.\d)?\)[^\n]*?\*\*WRITE THIS COPY\*\* — client asks for: «/gm
export const SOURCE_AN_IMAGE_RE =
  /^\s*- \*\*Image slot\*\* [^(\n]*\((-?\d+(\.\d)?, ){3}-?\d+(\.\d)?\)[^\n]*?\*\*SOURCE AN IMAGE\*\* — no upload; client wants: «/gm

const WALKTHROUGH_BULLET_RE = /^[ \t]*- \*\*(Nav bar|Heading|Text|Button|Image slot)\*\*/gm
/** Honors rule-7 escaping so an escaped `»` cannot close a quote early. */
const QUOTE_RE = /«((?:\\[\s\S]|[^»\\])*)»/g
/**
 * `reg` and `set` join the printed-id family in the same edit that publishes them,
 * not in the one that starts printing them. §3.3 rule 5 says every id the brief
 * prints must exist in `site.json`; a region id is now such an id, and adding it
 * later would mean shipping one release in which the brief could cite a region
 * that does not exist and nothing would notice.
 *
 * Matched on the MINTED shape, not a loose `[a-z0-9]` body. §4.8 mints every public
 * id as its prefix + zero-padded DIGITS (`ordinalId`, `ORDINAL_DIGITS` = 4; `img_` is
 * a three-digit asset ordinal). Letters after the underscore never occur in a real
 * id, so a client filename that reads like one — `set_menu.jpg`, `reg_flow.png` for a
 * restaurant — must not be mistaken for an id the brief invented and BLOCK a valid
 * package (§5 V7). This still matches every real printed id, whose body is all digits.
 */
const PRINTED_ID_RE = /\b(?:img_[0-9]{3}|(?:pg|blk|nav|stk|reg|set)_[0-9]{4,16})\b/g

/**
 * §3.3 rule 2 — the counted marker for a drawn region, matched the same way
 * WRITE THIS COPY and SOURCE AN IMAGE are: anchored to a bullet, so the DoD
 * boilerplate and any prose that merely names the marker cannot be counted.
 */
export const BUILD_FROM_INK_RE = /^[ \t]*- \*\*[^\n]*?\*\*BUILD THIS FROM INK\*\*/gm
const COPY_LIST_ITEM_RE = /^\d+\. \*\*/gm

/**
 * The two guillemet spans in the fixed boilerplate are template prose, not client
 * text, and are exempt from the «…» cross-check (§5 V7).
 */
const EXEMPT_QUOTES = new Set(['…', 'X'])

/** §4.4 [N5]/[N7] truncation, for the derived-form comparison. */
const TRUNCATE_CHARS = 40

const countMatches = (text: string, pattern: RegExp): number =>
  (text.match(new RegExp(pattern.source, pattern.flags)) ?? []).length

const normalizeWs = (value: string): string => value.replace(/\s+/g, ' ').trim()
const glyphed = (value: string): string => value.replace(/\r\n|\r|\n/g, '↵')
const truncate40 = (value: string): string =>
  value.length > TRUNCATE_CHARS ? `${value.slice(0, TRUNCATE_CHARS)}…` : value

function sections(brief: string): Map<string, string> {
  const out = new Map<string, string>()
  let title = '(preamble)'
  let buffer: string[] = []

  for (const line of brief.split('\n')) {
    const heading = /^## (.+?)\s*$/.exec(line)
    if (heading) {
      out.set(title, buffer.join('\n'))
      title = heading[1] ?? ''
      buffer = []
      continue
    }
    buffer.push(line)
  }
  out.set(title, buffer.join('\n'))
  return out
}

function problemsForProvenance(brief: string, site: SiteJson): string[] {
  const match = /<!--\s*Generated by BOSS Blueprint([\s\S]*?)-->/.exec(brief)
  if (!match) return ['brief.md has no "Generated by BOSS Blueprint …" provenance comment (§6.7)']

  const header = match[1] ?? ''
  return (
    [
      [site.submission.appVersion, 'appVersion'],
      [site.submission.id, 'submission.id'],
      [site.submission.submittedAt, 'submittedAt'],
      [String(site.schemaVersion), 'schemaVersion'],
    ] as const
  )
    .filter(([value]) => value !== '' && !header.includes(value))
    .map(([value, label]) => `provenance header does not carry ${label} "${value}"`)
}

function problemsForMarkers(brief: string, site: SiteJson): string[] {
  const problems: string[] = []
  const writes = countMatches(brief, WRITE_THIS_COPY_RE)
  const sources = countMatches(brief, SOURCE_AN_IMAGE_RE)

  if (writes !== generateBlocks(site).length) {
    problems.push(
      `WRITE THIS COPY markers: brief has ${String(writes)}, site.json has ${String(generateBlocks(site).length)} generate block(s)`,
    )
  }
  if (sources !== emptySlots(site).length) {
    problems.push(
      `SOURCE AN IMAGE markers: brief has ${String(sources)}, site.json has ${String(emptySlots(site).length)} empty image slot(s)`,
    )
  }
  return problems
}

function problemsForInventory(brief: string, site: SiteJson): string[] {
  const problems: string[] = []

  site.pages.forEach((page, index) => {
    const heading = `### Page ${String(index + 1)} — ${escapeClientText(page.name)} (\`${page.slug}\`)`
    if (!brief.includes(heading)) problems.push(`walkthrough heading missing or wrong: expected "${heading}"`)
  })

  const inventory = sections(brief).get('Site inventory')
  if (inventory === undefined) return [...problems, 'brief.md has no "## Site inventory" section']

  const rows = inventory
    .split('\n')
    .filter((line) => /^\| \d+ \| /.test(line.trim()))
    .map((line) => line.trim().split('|').slice(1, -1).map((cell) => cell.trim()))

  if (rows.length !== site.pages.length) {
    return [...problems, `site inventory has ${String(rows.length)} row(s), site.json has ${String(site.pages.length)} page(s)`]
  }

  site.pages.forEach((page, index) => {
    const cells = rows[index] ?? []
    // v2.5 — the Blocks cell counts the page's TOP-LEVEL drawn regions alongside its
    // blocks, so a page the client drew rather than blocked out does not advertise
    // itself as empty. Byte-neutral, and still exactly one cell, when there are none.
    const drawn = (page.penRegions ?? []).filter((region) => region.parentRegionId === null).length
    const expected = [
      String(index + 1),
      escapeClientText(page.name),
      `\`${page.slug}\``,
      `\`${page.screenshot}\` (${String(EXPORT_PAGE_WIDTH)}×${String(page.height)})`,
      drawn === 0 ? String(page.blocks.length) : `${String(page.blocks.length)} (+${String(drawn)} drawn)`,
    ]
    expected.forEach((want, column) => {
      if (cells[column] !== want) {
        problems.push(`inventory row ${String(index + 1)} column ${String(column + 1)}: "${cells[column] ?? ''}" != "${want}"`)
      }
    })
  })
  return problems
}

function problemsForCounts(brief: string, site: SiteJson): string[] {
  const problems: string[] = []
  const parts = sections(brief)

  const walkthrough = parts.get('Page walkthroughs')
  if (walkthrough === undefined) {
    problems.push('brief.md has no "## Page walkthroughs" section')
  } else {
    const bullets = countMatches(walkthrough, WALKTHROUGH_BULLET_RE)
    const nonSection = eachBlock(site).filter(({ block }) => block.type !== 'section').length
    if (bullets !== nonSection) {
      problems.push(`walkthrough bullets: brief has ${String(bullets)}, site.json has ${String(nonSection)} non-section block(s)`)
    }
  }

  const copyTitle = [...parts.keys()].find((title) => title.startsWith('Copy you must write'))
  // v2.5 — the heading counts the NUMBERED LIST under it, which is the `generate`
  // blocks. Copy that comes from ink is stated after the list with its own verbs and
  // its own counts, so the heading's number stands for exactly one thing and V7 has
  // one copy-list number to check instead of two that had to be kept apart.
  const generateCount = generateBlocks(site).length
  if (copyTitle === undefined) {
    problems.push('brief.md has no "## Copy you must write" section')
  } else {
    const header = /^Copy you must write \((\d+) (item|items)\)$/.exec(copyTitle)
    if (!header) {
      problems.push(`copy-list header "${copyTitle}" does not match "Copy you must write (N item|items)"`)
    } else {
      if (Number(header[1]) !== generateCount) {
        problems.push(
          `copy-list header says ${header[1] ?? ''}, site.json has ${String(generateCount)} generate block(s)`,
        )
      }
      const wantWord = generateCount === 1 ? 'item' : 'items'
      if (header[2] !== wantWord) problems.push(`copy-list pluralization "${header[2] ?? ''}" should be "${wantWord}" [N8]`)
    }
    const items = countMatches(parts.get(copyTitle) ?? '', COPY_LIST_ITEM_RE)
    if (items !== generateCount) {
      problems.push(`copy-list items: brief has ${String(items)}, site.json has ${String(generateCount)}`)
    }
  }

  const assets = parts.get('Assets')
  if (assets === undefined) {
    problems.push('brief.md has no "## Assets" section')
  } else {
    const entries = assets.split('\n').filter((line) => /^- `assets\/img_\d{3}\./.test(line)).length
    if (entries !== site.assets.length) {
      problems.push(`assets section has ${String(entries)} entr(y/ies), the manifest has ${String(site.assets.length)}`)
    }
  }
  return problems
}

function problemsForPrintedIds(brief: string, site: SiteJson): string[] {
  const known = new Set<string>()
  for (const page of site.pages) {
    known.add(page.id)
    for (const block of page.blocks) {
      known.add(block.id)
      if (block.type === 'navBar') for (const item of block.items) known.add(item.id)
    }
    for (const stroke of page.penStrokes) known.add(stroke.id)
    for (const region of page.penRegions ?? []) {
      known.add(region.id)
      if (region.setId !== null) known.add(region.setId)
    }
  }
  for (const asset of site.assets) known.add(asset.id)

  const printed = new Set(brief.match(PRINTED_ID_RE) ?? [])
  return [...printed]
    .filter((id) => !known.has(id))
    .map((id) => `brief prints id \`${id}\` which does not exist in site.json (§3.3 rule 5)`)
}

/**
 * Every «…» quote must match a `site.json` string in one of the DEFINED derived
 * forms (v2.1): verbatim, `↵`-glyphed, or — when it ends with `…` — the 40-char
 * truncation. Comparison happens after reversing the rule-7 escapes and is
 * whitespace-normalized.
 */
function problemsForQuotes(brief: string, site: SiteJson): string[] {
  const verbatim = new Set<string>()
  const prefixes: string[] = []

  for (const { value } of eachClientString(site)) {
    const plain = normalizeWs(value)
    const glyph = normalizeWs(glyphed(value))
    verbatim.add(plain)
    verbatim.add(glyph)
    verbatim.add(normalizeWs(truncate40(value)))
    verbatim.add(normalizeWs(truncate40(glyphed(value))))
    prefixes.push(plain, glyph)
  }

  const problems: string[] = []
  const seen = new Set<string>()
  const pattern = new RegExp(QUOTE_RE.source, QUOTE_RE.flags)

  let match = pattern.exec(brief)
  while (match !== null) {
    const raw = unescapeClientText(match[1] ?? '')
    const quoted = normalizeWs(raw)
    if (!EXEMPT_QUOTES.has(raw) && !seen.has(quoted)) {
      seen.add(quoted)
      const isTruncatedPrefix =
        quoted.endsWith('…') && prefixes.some((field) => field.startsWith(quoted.slice(0, -1)))
      if (!verbatim.has(quoted) && !isTruncatedPrefix) {
        problems.push(`brief quotes «${quoted.slice(0, 60)}» which matches no site.json string in any derived form`)
      }
    }
    match = pattern.exec(brief)
  }
  return problems
}

/**
 * V30 — exactly one `**BUILD THIS FROM INK**` marker per TOP-LEVEL region,
 * site-wide.
 *
 * The same count invariant V7 already runs for WRITE THIS COPY and SOURCE AN
 * IMAGE, and it is here for the same reason: a region the brief never mentions is
 * ink the client drew and the builder never sees, and `clustersOf` no longer
 * narrates it as an annotation either — the coupling that stops the double
 * narration is exactly what makes a missing marker silent without this rule.
 *
 * TOP-LEVEL only: a nested writing region is described INSIDE its parent's bullet
 * ("a box with 2 lines of handwriting inside"), so counting it separately would
 * demand a bullet that must not exist.
 */
export function v30BuildFromInkMarkers({ site, brief }: PackageBundle): Finding[] {
  const expected = site.pages
    .flatMap((page) => page.penRegions ?? [])
    .filter((region) => region.parentRegionId === null).length

  if (brief === null) {
    return expected === 0
      ? []
      : [finding('V30', 'BLOCK', 'bug', 'brief.md is missing — nothing describes the drawn regions', [])]
  }

  const actual = countMatches(brief, BUILD_FROM_INK_RE)
  return actual === expected
    ? []
    : [
        finding(
          'V30',
          'BLOCK',
          'bug',
          `BUILD THIS FROM INK markers: brief has ${String(actual)}, site.json has ${String(expected)} top-level pen region(s)`,
          [],
        ),
      ]
}

/** V7 — one BLOCK finding per drifted cross-check. */
export function v07BriefCrossCheck({ site, brief }: PackageBundle): Finding[] {
  if (brief === null) {
    return [finding('V07', 'BLOCK', 'bug', 'brief.md is missing — nothing to cross-check', [])]
  }

  return [
    ...problemsForProvenance(brief, site),
    ...problemsForMarkers(brief, site),
    ...problemsForInventory(brief, site),
    ...problemsForCounts(brief, site),
    ...problemsForPrintedIds(brief, site),
    ...problemsForQuotes(brief, site),
  ].map((problem) => finding('V07', 'BLOCK', 'bug', problem, []))
}
