/**
 * export-format.md §5 V7 — brief cross-checks (generator drift), plus the
 * [N13] right-overflow marker consistency check reported under its own id.
 *
 * V7 is a bundle of independent cross-checks in the spec; this module implements
 * every one and reports them as one BLOCK-class check with itemised problems, so
 * a failure names exactly which cross-check drifted.
 */

import { check } from '../report.mjs';
import { pagesOf, assetsOf, blocksOf, eachBlock, eachString, frameOf } from './walk.mjs';
import { overflowingBlocks } from './links-frames.mjs';
import {
  WRITE_THIS_COPY_RE,
  SOURCE_AN_IMAGE_RE,
  WALKTHROUGH_BULLET_RE,
  QUOTE_RE,
  PRINTED_ID_RE,
  N13_MARKER,
  countMatches,
  sections,
  sectionStartingWith,
  escapeClientText,
  unescapeClientText,
  newlineGlyph,
  normalizeWs,
  truncate40,
  frameTuple,
} from '../brief-parse.mjs';

export function v7BriefCrossChecks(pkg, ctx) {
  const site = pkg.site;
  const brief = pkg.briefText?.text ?? null;
  if (brief === null || site === null) {
    return check({
      id: 'V07',
      title: 'brief.md cross-checks against site.json (generator drift)',
      ref: 'export-format §5 V7 / §3.3',
      cls: 'BLOCK',
      problems: [brief === null ? 'brief.md is missing or unreadable' : 'site.json unparseable — cannot cross-check'],
      ...ctx,
    });
  }

  const problems = [];
  const secs = sections(brief);
  const pages = pagesOf(site);

  problems.push(...checkProvenanceHeader(brief, site));
  problems.push(...checkMarkerCounts(brief, site));
  problems.push(...checkHeadingsAndInventory(brief, secs, pages));
  problems.push(...checkWalkthroughBullets(secs, site));
  problems.push(...checkCopyList(secs, site));
  problems.push(...checkAssetsSection(secs, site));
  problems.push(...checkPrintedIds(brief, site));
  problems.push(...checkQuotes(brief, site));

  return check({
    id: 'V07',
    title: 'brief.md cross-checks against site.json (markers, inventory, ids, quotes)',
    ref: 'export-format §5 V7 / §3.3 rules 2, 5, 7, 8',
    cls: 'BLOCK',
    problems,
    detail:
      `${countMatches(brief, WRITE_THIS_COPY_RE)} WRITE THIS COPY, ` +
      `${countMatches(brief, SOURCE_AN_IMAGE_RE)} SOURCE AN IMAGE, ` +
      `${countMatches(brief, WALKTHROUGH_BULLET_RE)} block bullets`,
    ...ctx,
  });
}

/** §6.7 — the brief's HTML comment header carries appVersion, submission id, timestamp, schemaVersion. */
function checkProvenanceHeader(brief, site) {
  const problems = [];
  const m = /<!--\s*Generated by BOSS Blueprint([\s\S]*?)-->/.exec(brief);
  if (!m) return ['brief.md has no "Generated by BOSS Blueprint …" provenance comment (§3.2 / §6.7)'];
  const header = m[1];
  const wants = [
    [site?.submission?.appVersion, 'appVersion'],
    [site?.submission?.id, 'submission.id'],
    [site?.submission?.submittedAt, 'submittedAt'],
    [String(site?.schemaVersion), 'schemaVersion'],
  ];
  for (const [value, label] of wants) {
    if (typeof value === 'string' && value && !header.includes(value)) {
      problems.push(`brief provenance header does not carry ${label} "${value}"`);
    }
  }
  return problems;
}

/** §3.3 rule 2 — frame-tuple-anchored marker counts. */
function checkMarkerCounts(brief, site) {
  const problems = [];
  const generateBlocks = eachBlock(site).filter(({ block }) => block?.copyMode === 'generate');
  const emptySlots = eachBlock(site).filter(({ block }) => block?.type === 'imageSlot' && block.assetId === null);

  const writeCount = countMatches(brief, WRITE_THIS_COPY_RE);
  if (writeCount !== generateBlocks.length) {
    problems.push(
      `WRITE THIS COPY markers: brief has ${writeCount}, site.json has ${generateBlocks.length} generate block(s)`,
    );
  }
  const sourceCount = countMatches(brief, SOURCE_AN_IMAGE_RE);
  if (sourceCount !== emptySlots.length) {
    problems.push(
      `SOURCE AN IMAGE markers: brief has ${sourceCount}, site.json has ${emptySlots.length} empty image slot(s)`,
    );
  }
  return problems;
}

/** Page slug headings + the Site inventory table. */
function checkHeadingsAndInventory(brief, secs, pages) {
  const problems = [];

  pages.forEach((page, i) => {
    const heading = `### Page ${i + 1} — ${escapeForCompare(page?.name)} (\`${page?.slug}\`)`;
    if (!brief.includes(heading)) {
      problems.push(`walkthrough heading missing or wrong: expected "${heading}"`);
    }
  });

  const inventory = secs.get('Site inventory');
  if (inventory === undefined) return [...problems, 'brief.md has no "## Site inventory" section'];

  // [N11] v2.3: the inventory count line pluralizes — "1 page" / "N pages".
  const wantCount = `${pages.length} ${pages.length === 1 ? 'page' : 'pages'}. **Page 1 is the homepage.**`;
  if (!inventory.includes(wantCount)) {
    problems.push(`site inventory count line is not "${wantCount}" [N11]`);
  }

  const rows = inventory
    .split('\n')
    .filter((l) => /^\|/.test(l.trim()))
    .map((l) => l.trim().split('|').slice(1, -1).map((c) => c.trim()))
    .filter((cells) => cells.length >= 6 && /^\d+$/.test(cells[0]));

  if (rows.length !== pages.length) {
    problems.push(`site inventory has ${rows.length} page row(s), site.json has ${pages.length}`);
    return problems;
  }

  pages.forEach((page, i) => {
    const [n, name, slug, sketch, blocks] = rows[i];
    if (n !== String(i + 1)) problems.push(`inventory row ${i + 1}: index cell is "${n}"`);
    if (unescapeClientText(name) !== page?.name) {
      problems.push(`inventory row ${i + 1}: page name "${unescapeClientText(name)}" != site.json "${page?.name}"`);
    }
    if (slug !== `\`${page?.slug}\``) problems.push(`inventory row ${i + 1}: slug cell "${slug}" != \`${page?.slug}\``);
    const wantSketch = `\`${page?.screenshot}\` (1200×${page?.height})`;
    if (sketch !== wantSketch) problems.push(`inventory row ${i + 1}: sketch cell "${sketch}" != "${wantSketch}"`);
    const wantBlocks = String(blocksOf(page).length);
    if (blocks !== wantBlocks) problems.push(`inventory row ${i + 1}: block count "${blocks}" != ${wantBlocks}`);
  });

  return problems;
}

/** Walkthrough block bullets == non-section block count site-wide. */
function checkWalkthroughBullets(secs, site) {
  const body = secs.get('Page walkthroughs');
  if (body === undefined) return ['brief.md has no "## Page walkthroughs" section'];
  const bullets = countMatches(body, WALKTHROUGH_BULLET_RE);
  const nonSection = eachBlock(site).filter(({ block }) => block?.type !== 'section').length;
  return bullets === nonSection
    ? []
    : [`walkthrough block bullets: brief has ${bullets}, site.json has ${nonSection} non-section block(s)`];
}

/** Copy-list header count and item count == generate-block count. */
function checkCopyList(secs, site) {
  const problems = [];
  const found = sectionStartingWith(secs, 'Copy you must write');
  if (!found) return ['brief.md has no "## Copy you must write" section'];
  const generateCount = eachBlock(site).filter(({ block }) => block?.copyMode === 'generate').length;

  const headerMatch = /^Copy you must write \((\d+) (item|items)\)$/.exec(found.title);
  if (!headerMatch) {
    problems.push(`copy-list header "${found.title}" does not match "Copy you must write (N item|items)"`);
  } else {
    if (Number(headerMatch[1]) !== generateCount) {
      problems.push(`copy-list header says ${headerMatch[1]}, site.json has ${generateCount} generate block(s)`);
    }
    const wantWord = generateCount === 1 ? 'item' : 'items';
    if (headerMatch[2] !== wantWord) problems.push(`copy-list header pluralization "${headerMatch[2]}" should be "${wantWord}" [N8]`);
  }

  const items = countMatches(found.body, /^\d+\. \*\*/gm);
  if (items !== generateCount) problems.push(`copy-list items: brief has ${items}, site.json has ${generateCount}`);
  return problems;
}

/** Assets section: one entry per manifest asset, with matching dims and ~KB [N11]. */
function checkAssetsSection(secs, site) {
  const problems = [];
  const body = secs.get('Assets');
  if (body === undefined) return ['brief.md has no "## Assets" section'];
  const assets = assetsOf(site);
  const entryLines = body.split('\n').filter((l) => /^- `assets\/img_\d{3}\.[a-z]+`/.test(l));
  if (entryLines.length !== assets.length) {
    problems.push(`assets section has ${entryLines.length} entr(y/ies), site.json manifest has ${assets.length}`);
  }
  for (const asset of assets) {
    const line = entryLines.find((l) => l.startsWith(`- \`${asset.path}\``));
    if (!line) {
      problems.push(`assets section has no entry for "${asset.path}"`);
      continue;
    }
    const wantDims = `${asset.width}×${asset.height}`;
    if (!line.includes(wantDims)) problems.push(`assets entry for ${asset.id} does not print "${wantDims}"`);
    const wantKb = `~${Math.round(asset.bytes / 1024)} KB`;
    if (!line.includes(wantKb)) problems.push(`assets entry for ${asset.id} does not print "${wantKb}" [N11]`);
  }
  return problems;
}

/** §3.3 rule 5 — every id printed in the brief exists in site.json. */
function checkPrintedIds(brief, site) {
  const known = new Set();
  for (const page of pagesOf(site)) {
    known.add(page?.id);
    for (const block of blocksOf(page)) {
      known.add(block?.id);
      if (Array.isArray(block?.items)) for (const item of block.items) known.add(item?.id);
    }
    for (const stroke of Array.isArray(page?.penStrokes) ? page.penStrokes : []) known.add(stroke?.id);
  }
  for (const asset of assetsOf(site)) known.add(asset?.id);

  const problems = [];
  const seen = new Set();
  const rx = new RegExp(PRINTED_ID_RE.source, PRINTED_ID_RE.flags);
  let m;
  while ((m = rx.exec(brief)) !== null) {
    const id = m[0];
    if (seen.has(id)) continue;
    seen.add(id);
    if (!known.has(id)) problems.push(`brief prints id \`${id}\` which does not exist in site.json (§3.3 rule 5)`);
  }
  return problems;
}

/**
 * §4.4 "Reference text" (v2.3, shared by [N5]/[N7]/[N8]) — the string those rules print
 * for a referenced block. Not always a bare field: a generate block references its
 * `generateDescription` (never its residual `text`), and a navBar references its item
 * labels joined with ", ", which exists nowhere in site.json as a single value.
 */
function referenceTexts(site) {
  const out = [];
  for (const { block } of eachBlock(site)) {
    switch (block?.type) {
      case 'heading':
      case 'text':
        out.push(block.copyMode === 'generate' ? block.generateDescription : block.text);
        break;
      case 'button':
        out.push(block.label);
        break;
      case 'imageSlot':
        out.push(block.description);
        break;
      case 'navBar':
        out.push((Array.isArray(block.items) ? block.items : []).map((i) => i?.label ?? '').join(', '));
        break;
      default:
        break; // section blocks are never referenced
    }
  }
  return out.filter((s) => typeof s === 'string');
}

/**
 * Every «…»-quoted string matches a site.json string field — or a §4.4 reference text —
 * in one of the defined derived forms: verbatim, ↵-glyphed, or (when it ends with …) a
 * 40-char prefix. Comparison is whitespace-normalized, after reversing rule-7 escapes.
 * v2.3 truncates the RAW string to 40 first and escapes after, so reversing the escapes
 * before comparing keeps the two sides aligned.
 */
function checkQuotes(brief, site) {
  const exempt = new Set(['…', 'X']);
  const fields = [...eachString(site).map((s) => s.value), ...referenceTexts(site)];
  const verbatim = new Set();
  const prefixes = [];
  for (const f of fields) {
    const plain = normalizeWs(f);
    const glyphed = normalizeWs(newlineGlyph(f));
    verbatim.add(plain);
    verbatim.add(glyphed);
    verbatim.add(normalizeWs(truncate40(f)));
    verbatim.add(normalizeWs(truncate40(newlineGlyph(f))));
    prefixes.push(plain, glyphed);
  }

  const problems = [];
  const seen = new Set();
  const rx = new RegExp(QUOTE_RE.source, QUOTE_RE.flags);
  let m;
  while ((m = rx.exec(brief)) !== null) {
    const raw = unescapeClientText(m[1]);
    if (exempt.has(raw)) continue;
    const q = normalizeWs(raw);
    if (seen.has(q)) continue;
    seen.add(q);
    if (verbatim.has(q)) continue;
    if (q.endsWith('…')) {
      const head = q.slice(0, -1);
      if (prefixes.some((f) => f.startsWith(head))) continue;
    }
    problems.push(`brief quotes «${q.slice(0, 60)}» which matches no site.json string field in any derived form`);
  }
  return problems;
}

/** [N13] — right-overflow marker present exactly on the overflowing blocks' bullets. */
export function n13OverflowMarker(pkg, ctx) {
  const brief = pkg.briefText?.text ?? null;
  const site = pkg.site;
  if (brief === null || site === null) {
    return check({
      id: 'N13',
      title: '[N13] right-overflow marker consistency',
      ref: 'export-format §4.4 [N13] / §5 V25',
      cls: 'BLOCK',
      skipped: true,
      ...ctx,
    });
  }
  const overflow = overflowingBlocks(site);
  const markerCount = brief.split(N13_MARKER).length - 1;
  const problems = [];
  if (markerCount !== overflow.length) {
    problems.push(`[N13] markers in brief: ${markerCount}, blocks with x + w > 1200: ${overflow.length}`);
  }
  const lines = brief.split('\n');
  for (const { block } of overflow) {
    const f = frameOf(block);
    if (!f) continue;
    const tuple = frameTuple(f);
    const bullet = lines.find((l) => l.includes(tuple) && /^[ \t]*- \*\*/.test(l));
    if (!bullet) {
      problems.push(`no walkthrough bullet found carrying frame ${tuple} for overflowing block ${block.id}`);
    } else if (!bullet.includes(N13_MARKER)) {
      problems.push(`block ${block.id} overflows to x=${f.x + f.w} but its bullet carries no [N13] marker`);
    }
  }
  return check({
    id: 'N13',
    title: '[N13] right-overflow marker appears on exactly the overflowing blocks’ bullets',
    ref: 'export-format §4.4 [N13]',
    cls: 'BLOCK',
    problems,
    detail: `${overflow.length} overflowing block(s), ${markerCount} marker(s)`,
    ...ctx,
  });
}

/** §3.3 rule 7 (v2.4) escaping, so a brief-side value can be compared to a site.json value. */
const escapeForCompare = escapeClientText;
